### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by fredgit** [fabiomsr/drawable-optimizer#2]
java.lang.UnsupportedClassVersionError: org/fabiomsr/drawableoptimizer/DrawableOptimizerPlugin : Unsupported major.minor version 52.0

Hi, should I use java 1.8 to compile? Thanks.

**Comment by cosic** [comment]
@fredgit I guess you met the same problem that discussed for [retrolambda](https://github.com/evant/gradle-retrolambda/issues/74) plugin

**Comment by fabiomsr** [comment]
I have compiled a new version with java 1.6.

`classpath 'org.fabiomsr:drawable-optimizer-gradle-plugin:1.0.4'`

**Comment by fredgit** [comment]
@cosic @fabiomsr Cool. Thanks.
